---
version: '3'

services:
  kitkatch:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/kitkatch
    entrypoint: tail -f /dev/null
    working_dir: /opt/kitkatch
    environment:
      - PYTHONPATH=/opt/kitkatch
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
    ports:
      - 8088:8080
      - 8089:80
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./testdata:/app
      - ./server_configs/httpd.conf:/vhosts/my_vhost.conf:ro
